#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* プロローグ-02

  かつての聖都へと続く道。魔物と人との戦線を抜け出し，エスは血と骨に彩
  られた悪臭のなかを進んだ。エスはこれまでにないほどの興奮を感じていた。
  それは死と叫びが支配する世界に立っているというだけでなく，黒檀の刃が
  もたらす圧倒的な力によるところが大きい。

  黒檀の武器を扱う者には冷静さと猛りの双方が求められる。ふだんは刃が鈍
  い漆黒を帯びており，敵を斬るたびに興奮が高まってゆく。冷静さは自ら攻
  撃するだけでなく，敵から攻撃を受けたり，防御することでも失われてゆく。
  そして冷静さが完全に失われると，黒檀の戦士は猛りと呼ばれる状態になる。

  猛りにある黒檀の戦士は，鉄綿を燃やすような淡い炎を身体に帯びる。それ
  とともに刃は赤熱し，切れ味が大きく増すが，攻撃のたびにエス自身の肉体
  が焦がされてゆく。それはまるで自らを燃やしながら敵を屠っていくかのよ
  うに見える。

  ただし刃の力によって焦がされる肉体は一時的なものである。猛りによって
  焦げた身体は，ひとたび冷静さを取り戻せば誓約の力によって瞬く間に再生
  する。しかし再生するのは猛りによって削られた肉体のみである。冷静さを
  失ったなかで敵に受けた傷は塞がらず，自らの手で癒さなければならない。

  黒檀の戦士の真髄は，たとえ敵の攻撃を受けても，心が冷静であれば身体が
  回避しダメージを受けないところにある。そして猛りにあるときでさえ，戦
  いへの集中はさらに高まる。敵へのカウンター攻撃時に急所を狙うことでよ
  り強力なダメージを与えられるのだ。

  こうした無敵にも思える黒檀の戦士には，魂が潰えるまで決して死ぬことが
  できないという代償がある。たとえ身体が裂け，粉々に砕けても，魂がわず
  かでも残っている限りは結晶石の下に復活するのだ。当然ながら消えかけの
  魂がもつ刃などは何の役にも立たない。よってかつて黒檀の戦士だった者の
  多くは，それまで自身を頼ってきた味方によって始末されてしまう。

  比肩するもののない力と，そこからは想像もできないほどの無残な最後。そ
  れゆえ黒檀の誓約を結ぶ者は少なく，仮に誓約を結び，国のために戦ったと
  しても，その栄誉が称えられることは殆どなかった。それにも関わらずエス
  が誓約を結んだのも，ひとえに戦乱から妹を守るためであった。仮に彼女が
  聖都にいるのなら，すべての敵を滅ぼしてでも救うという，揺るぎない覚悟
  があった。


  <br>
  <br>

  [[./03.md][プロローグ-03へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

