#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-01

  幻魔王の使い魔カーリオンと別れたエスは塔の空洞を通路沿いに進んだ。柱
  の隙間から見える空洞はどこまでも漆黒で満たされており，時おり唸り声の
  ような反響が鼓膜を揺らすのであった。

  先の激戦地からみて塔の反対側へとたどり着いた。ここだけは柱が崩れて広
  場になっており，その中央には結晶石がある。そしてその奥にたつ巨大な扉
  から何かの気配が黒く漏れだしているのがわかった。

  広場は地面が荒れはてており，剣の破片や布の切れ端が散らばっている。こ
  の先に鎮座する魔物との戦いによるものだろうか，死闘の跡がそこにあった。
  エスは結晶石に腰をおろし，わずかな光を頼りに周囲を見回した。

  塔の頂上ははるか高く，ここからは見えない。エスが通ってきたのと同様の
  通路らしきものが上にまで続いているようだが，塔の破損は激しく，よほど
  の近道でもないかぎりは炎塔を灯していた火の抜け殻まで行くことはできな
  いだろう。

  エスは立ち上がり，覚悟を決めて扉に進んだ。扉からは何かが飛び出してく
  るような気配はない。扉の前は瓦礫でやや盛り上っており，その影から敵が
  出てきてもいいよう警戒しながら登ってゆく。

  扉まで残り十歩程度となったときのことである。突如，エスは自身の不意を
  恥じた。エスはこの瓦礫の山が扉の先にいる敵によってできたものだと確信
  していた。しかしそれなら，攻撃は前から来るはずだから，ふきとばされた
  瓦礫は当然，自身の後方，柱や空洞のほうに積もるはずである。

  すなわちこの瓦礫や広場は前方の敵によるものでなく後方の

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/meltystomach/02.md][燃えさかる腹-02へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

