#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-03

  初めの一撃は手応えがあった。だが敵はひるむ様子もなく，続く攻撃を弾く。
  さらに背中一面にトゲを生やし，倒れ込むように転がってきたのだ。あわて
  てエスは後退し脇道に逃れる。魔物は球状のまま直進しつづけ，壁に激突し
  て止まった。身ぶるいをして人型に戻る。

  エスが脇道から出ると，再び球状になり転がってきた。やむをえずエスは後
  退する。その前をトゲの球体が通過する。だがエスはこの先に起きる危機を
  理解していた。

  足音が近付き，壁の影から敵が姿を現した。エスが真正面から攻撃するのを
  もろともせず，鎌を振り下ろす。続けて肩をいからせ体当たりをしてきた。
  鎌は避けたものの，範囲の広いタックルを受けエスは体勢を崩す。そこへ鎌
  がつきたてられ，そのままボロ切れのように投げ捨てられた。

  エスは自身が受けたダメージよりも，この先に敵がとる戦術を予測し，付近
  の地形を必死に思い出した。投げられて距離があいたところで敵は球体にな
  り，押し潰そうとしてきたのだ。起きあがったエスは後退し，なんとか横道
  に飛び込んだ。

  正面の壁に激突し，形状を変えようとするところを横から突くと，ようやく
  相手は力尽きた。これだけ手こずる敵がこの先何体も待ちかまえているのだ。
  先に見た兵士の亡骸が頭をよぎった。

  
  




  <br>
  <br>
  燃えさかる腹-04へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

