#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-05

  石組みの道を戻りながら，エスは熱が引いているのを感じた。それが確信に
  変わったのは，底の抜けた穴をのぞいたとき，以前のような溶岩がすっかり
  消えているのを見たときである。

  かつての溶岩池はその面影すらなく，大きな空洞になっていた。そこから下
  へ続く階段がある。またこちらを一方的に攻撃していたトカゲの魔物は地面
  にはいつくばっているのがわかった。溶岩が引いたことで弱っていること期
  待したがそれは叶えられなかったようだ。

  階段を下ると，トカゲの群れは腹這いのまま左右に身体をくねらせ一気に近
  付いてきた。エスも激昂して応戦する。しかし驚くほど敵は硬く，ダメージ
  が通っていないのを感じた。それでも攻撃をしつづけ，ようやくその群れを
  始末したころにはエスの生命力は残りわずかとなっていた。

  敵は数で押してくるうえ，個々の体力がトゲの魔物ほどあるとは思えなかっ
  た。にも関わらずこれだけ苦戦するのは，いまの実力が足りないか，不適な
  戦術をとっていることになる。

  エスは一旦結晶石に帰還し，座り込んで思案した。相変わらず低く震えるよ
  うな音が響いてくる。それは溶岩の流れが引いたことで余計に目立つのだっ
  た。

  ある考えに至り，エスは先を目指すこととした。溶岩池の跡には再びトカゲ
  の姿がある。階段を下ると，エスに気付いたトカゲの群れは再び迫ってきた。
  そこをエスは斬りつける。するとわずか数撃でトカゲは力尽きた。
  
  予想通りであった。溶岩に巣喰っていたこの敵は熱に強い。エスが興奮状態
  や激昂によって刃に熱を纏わせてしまうと，かえってダメージが減少してし
  まうのだ。言い換えれば，この敵に対し冷静さを失うと危険ということだ。

  普段はいかに刃を赤熱させ攻撃力を高めるか考えていたエスだが，ここにき
  ていかに冷静さを保つかが求められるようになった。冷静さはこちらが刃を
  ふるって攻撃するか，敵から攻撃を受けることで失われる。詠唱によって冷
  静さを失わない魔術であれば有利に戦えるだろう。
  
  エスは敵に囲まれないよう注意しつつ，かつ冷静さを失わないようにしなが
  らトカゲの群れを討伐していった。豪快な戦いを求めるエスにとって試練の
  時であった。
  

  <br>
  <br>
  燃えさかる腹-06へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

