#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-06

  トカゲの群れを始末したエスは，周囲を確認した。道はハシゴがかかってい
  た方に伸びる道と，階段から向かって正面の二手に分かれている。エスはハ
  シゴの方へ進んだ。

  その道はトゲの魔物達がいた通路の真下に位置しており，かつて溶岩へと続
  いていた穴も下から見えた。だがもはやエスや魔物を飲み込んだ灼熱の液体
  はない。トゲの魔物を倒すことは以前よりも困難になったとさえいえるだろ
  う。

  そこに新たな道は見当たらず，エスはもう一方の道へ進むことにした。道は
  徐々に熱を帯び，液体のわきたつ音が聞こえてきた。

  通路を抜けると，見渡す限りの広大な空間に，周囲には溶岩の滝がいくつも
  流れ，それは先の見えぬ虚無へと落ちていた。流れ落ちる赤とただれた茶色
  の壁がはるかかなたまで続いている。

  正面には磨かれた床がわずかに敷かれているものの，その先は寸断され，は
  るか下方へと落ちていた。その道の周囲には地面と呼べるものはない。暗黒
  である。だがかつて接続されていたであろう道がはるか前方に見えた。その
  道は下に穴が空いており，そこから流れ出る溶岩が下方にあるわずかな地
  面を打っている。

  その先は碗状の台座につながっていた。おそらく終点であろう。そこにはこ
  の灼熱地帯の主とおぼしき，漆黒の鎧をまとった巨人が佇んでいる。そして
  漆黒の巨人へたどり着く方法が必ずあるということも意味していた。

  エスは右手に登ってゆく道を発見し，そこから探索を始めることにした。削
  られた崖際は足を踏み外せば当然命はない。

  道は四角形の巨大なトンネルへとつながっていた。入る前に全容を確認
  したが，トンネルは宙に浮いているわけではなくいくつもの柱によって支え
  られているようだった。

  中へ入ると，驚いたことに兵士達の姿があった。だがいずれも正気を失って
  おり，エスの姿を見とめると襲いかかってきた。聖霊の加護なき兵士達はさ
  ほど脅威ではないが，聖都の防人である以上油断はできない。振りの大きな
  攻撃に合わせ，カウンターを合わせ倒していく。

  やがて行き止まりについた。いくつもの弧をえがく壁で仕切られた部屋の中
  央には，操作せよと言わんばかりの，ハンドルのついた台座がある。それを
  回してただで済むとは思わないが，覚悟のうえでエスは手を置いた。

  <br>
  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/meltystomach/07.md][燃えさかる腹-07へ]]

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

