#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-08

  結晶石にしゃがみ込んでいたエスは，先の敗戦は自身の不足によるものか振
  り返っていた。

  黒硝騎士サエルペンタス。戦闘が始まると地面に突き立てていた斧を構え，
  悠然と迫ってきた。攻撃は大振りで避けることはさほど難しくない。だが敵
  の最大の武器はその頑丈さにあった。

  全身を黒光りする鎧で覆い，その防御には一分の隙もない。エスの身体では
  騎士の膝ほどまでしか攻撃が届かず，仮に足を斬りつけてもガラスをこする
  ような不快な音しか立てない。攻撃が通らないのだ。

  稀に騎士が全身をかけて大地に攻撃を放つ。その際に，低い位置に下りてき
  た顔をめがけて渾身の一撃を見舞った。だが目まで覆う堅固な兜をエスの刃
  が貫けるはずもなかった。

  騎士が全くダメージを受けていないわけではない。ただし大岩を薄い布で触
  れるほどの些細なものである。確かに悠久の時をかけて攻撃しつづければ，
  やがて倒すことも不可能ではないだろう。だがそのためには，自身の刃が無
  力であることをエスが受け入れなければならなかった。

  どれほどの時間が経ったか。戦意を完全に喪失したエスは結晶石に復活して
  いた。もはやどのようにして自身の命が絶たれたかさえ覚えていない。結晶
  石の淡い光がゆらめいている。

  黒檀の戦士とは所詮この程度のものなのだろうか。それほどまでに敵は強大
  で，その圧倒的な力で聖霊を滅し，聖都を破壊しつくしたのだろうか。

  だがエスに葛藤することは許されていなかった。どれだけの時間がかかろう
  と倒せる相手であれば倒さなければならぬ。そして魂朽ちるまで，その思考
  は敵を倒すことにのみ費されるべきなのだ。

  エスは改めて挑戦することを決意し，再び灼熱の座へと進んでいったのだっ
  た。

  <br>
  <br>
  燃えさかる腹-09へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

