#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-09

  赤き滝が彩る灼熱の領域にエスは帰ってきた。騎士の待つ決戦場へ向け，ト
  ンネルを操作する。再び出現する兵士達と戦い，開かれた壁を抜け，その上
  へと駆けた。

  騎士は初めて対峙したときと変わらぬ様子で立っている。このまま戦いに挑
  んでも先刻の再現になるだけだ。エスは可能性の糸を求めトンネルの上をさ
  まよった。

  広大な領域を覆う褐色の壁。その下は永久の虚無。騎士の住まう座。エスの
  立つ磨かれたトンネル。そしてトンネルが接続される前，台座から流れる溶
  岩を受け止めていた皿のような地形と，ここへたどり着いたときに見た通路
  の一部が下方にあった。
  
  エスの立つ場所が接続される前，黒硝騎士サエルペンタスの立つ台座から流
  れる溶岩は受け皿に落ちていた。だが今はトンネルの先を経て流れ落ちてい
  る。エスはためらわず受け皿に飛び降りた。膝の砕ける音がしたが，治癒で
  回復する。そこから下方の通路が見えた。

  その通路にも先のトンネルと同様の穴が空いており，ここから跳躍するとちょ
  うどその穴の中へ到着するように見えた。エスは助走をつけて地面を蹴った。
  距離は際どかったものの，転がるように穴へ入った。
  
  内部はまさに先のトンネルとうりふたつであった。言い換えれば，奥のハン
  ドルを回し，押しよせる敵に対処すれば，道がひらかれることになる。だが
  トンネルの住人は厄介であった。
  
  兵士の代わりに住みついていたのはトカゲの魔物であった。エスを認めると，
  排除すべき対象として襲いかかってくる。この敵は兵士と違い，冷静さを失
  うと途端に不利になる敵だ。騎士との再戦に焦る気持ちを抑えつつエスは進
  んでいった。
  
  果たしてここにもハンドルがあった。周囲は弧をえがく壁で覆われている。
  エスは手の汗をぬぐい，ハンドルを回した。

  きしむ音が響きわたり，地面が動き出した。

  <br>
  <br>
  燃えさかる腹-10へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

