#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-04

  レバーは錆びつき，急いで引くと折れそうであった。それを慎重に下げると，
  歯車が回り出し，遠くで轟音が響くのがこちらまで届いた。おそらく水路の
  方角が変わったのだろう。

  歯車の側にははしごがあり，下に降りると薄暗く水の枯れた下水道へとつな
  がっていた。そこかしこに目だけが金色に輝く毛むくじゃらの魔物がはりつ
  いている。こちらに気付いても攻撃してこないのをみると，手出しをしない
  限りは敵意を持たない種類のようだ。

  それでも囲まれないように急いで下水道を駆けると，奥に見覚えがある格子
  状の門があった。金具を外し，門の下に手をかけ持ちあげると，結晶石が見
  えた。ここは街の入口につながっていたのだ。

  軽く休息をとってから，回転する水路へ向かうと，以前はトの字になってい
  た水路がTの字を描いている。次は左の道だ。先を見やると，これまでの街
  並みとは異なる薄暗さがあった。意図的に光を塞ぐような骨組みの建物が連
  なる。水路を天井を覆うように伸びた暗い建物群にエスは足を踏み入れた。

  足下は石から鉄板へと変わり，甲高い足音が周囲に反響する。鉄の錆びたに
  おいと死臭がたちこめ，建物のいたるところに格子が張ってあった。あたか
  も牢獄のような雰囲気に，何者かの荒い息づかいがこだまする。暗闇で全貌
  は把握できないが，人でないことだけはわかる。

  水路の先は瓦礫で行き止まりになっていた。戻って建物へと上がる道を探そ
  うとしたとき，背後の暗闇が割れ，赤黒い影が現れた。

  罪なき咎人ゲルダ。ずた袋をかぶった貧相な身なりのその敵は，やせ細った
  腕から幾本ものナイフを投げ攻撃してくる。中が空洞となったこのナイフに
  はいくつか穴が開いており，突き刺さるとおびただしい出血を強いるのだ。
  この領域で戦ってきた他の相手と同様に，この敵も出血攻撃を得意とするの
  だろう。

  逃げ場がない行き止まりの水路を活かし，敵はこちらを一方的に攻撃するつ
  もりのようだ。だが，単調な投擲であればエスでも回避できる。ゲルダの投
  擲に合わせて巧みに回避し，一気に距離を詰めた。

  するとゲルダは隠していたもう片方の手から丸い物体を取り出し投げつけて
  きた。とっさによけたエスをかすめて地面に当たると，破裂したそれは無数
  の針を放った。

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/05.md][水の都ローメシア-05へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

