#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* プロローグ-03

  荒れ果てた城門が見え，同時に臓物をにぎり潰されるほどの圧力をエスは感
  じた。暗闇に一瞬赤く筋が通る。次の瞬間，轟音とともにそれは大きく形を
  なした。

  針山の魔人。角張った石柱 -- おそらく城壁の一部だったもの -- を片手で
  構え，仁王立ちする怪物であった。魔人の頭部からは二本の角が生え，一見
  すると牛鬼のようでもあったが，全身が硬質の縮れた針で覆われていた。

  魔人はエスを確認すると，砂煙をあげ大きく吠えながら突進してきた。身の
  丈は並の人間の数倍はある。まともに攻撃を受ければ黒檀の戦士といえど身
  体が粉微塵になるだろう。

  エスは軽くステップを踏みながら周囲を確認した。厄介な取り巻きはいない。
  一対一の戦いのようだ。もしくは弱い魔物をこの魔人自体が屠ってしまった
  か。実際，周りには兵士だけでなくバラバラになった魔物が散乱している。
  同士打ちによって砕け散ったのかもしれない。

  改めて魔人を見た。針が生えているところは攻撃が通らないだろう。とすれ
  ば針のないところを攻撃するしかないが，それは目しかない。背の高い魔人
  に地上からの攻撃が届くわけもなく，かといって魔人の目に届くほどの跳躍
  力がエスにあるはずもない。一見すると打つ手がないように思える。だがエ
  スは落ち着いていた。

  エスは魔人の右腕に回り込むように移動したが，魔人の突進は精確だった。
  エスは武器をしまい，直前までひきつけてから大きく横っ飛びをした。魔人
  が勢いよく瓦礫に突っ込み，崩れた石の下敷きになった。手応えはどうか。
  わずかな静寂ののち，魔人が立ちあがった。

  魔人はダメージなど微塵もないかのように身震いし，身体の瓦礫を振り落と
  した。しかし自慢の突進が避けられたことは屈辱だったようだ。怒り狂った
  魔人はがむしゃらに石柱を振り回しながらエスに迫った。そして大きく振り
  かぶると，渾身の一撃を繰り出した。叩きつけられた石柱によって地面が大
  きく揺れ，その衝撃波でエスがバランスを崩す。すかさず魔人が石柱を薙ぎ
  払い，鈍い音とともにエスは紙くずのように宙空へ吹き飛ばされた。

  鮮血を引きながら空を舞うエス。しかしその目は勝利を確信していた。

  <br>
  <br>

  [[./04.md][プロローグ-04へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

