#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* プロローグ-04
 
  大きく吹き飛ばされたエスは背中から地面に叩きつけられると，魔人の追撃
  を逃れるべく横に転がりながら起き上がった。とどめを刺すべく向かってく
  る魔人。エスはすべるように魔人の足元をくぐると，すぐに振り返ってガラ
  空きの背中を見た。

  そこに魔人を護っていた針はなく，表皮がむきだしになっていた。

  先の突進で瓦礫が崩れおちたとき，岩が背中の鎧を砕いていたのである。

  ガラ空きの背中に刃を突き立てると，激しい血しぶきがあがった。魔人が大
  声でうなりながら前のめりになる。すかさず刃で幾度も切りつける。エスの
  肉が焦げる。それとともに魔人の身体もボロボロとはがれおちていく。

  やがてエスの息がきれた。天を仰いで大きく空気を吸い込む。血と肉の味を
  感じた。改めて前を見ると，そこには黒く溶けた残骸が散らばっていた。確
  認するまでもない。黒檀の戦士によって，聖都の門番は屠られたのだ。魔人
  の身体からわずかに光が生じると，それは形をなした。エスは近づいてその
  光を拾った。

  『魔人の逆針。ある人物に渡すことで，特別な戦技か魔術と交換できる。
  
  針山の魔人が全身に帯びていた針の一部。この一本だけ逆向きに生えてい
  る。この毛むくじゃらの魔物は殺戮の尖兵として多くの人々を喰らった』

  直後，エスは激痛に襲われた。黒檀の誓約は死の淵まで戦いを求める。ゆえ
  に，生命力が尽きなければ，戦闘に影響が出るような身体の損傷，たとえば
  筋肉の断裂や骨折，はては部位破損さえも先送りされる。それは戦闘の後，
  一度に肉体にふりかかるのだ。エスは付近にある建物の残骸に座り込み，震
  える身体でなんとか治癒を唱えた。

  崩れた城門を見た。還る者なき聖都。英雄たちを喰らった死の領域。そこで
  消息を絶った妹。エスにはある直感があった。妹はまだ生きている。よろよ
  ろと立ち上がり，エスは壁づたいに門に向かった。城門の先に広がる漆黒が
  黒檀の戦士を迎え入れようとしていた。

  <br>
  <br>

  [[../basecamp/01.md][最果ての地-01へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

