#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 聖樹の炎-05

  大樹の根元に灯るわずかな火，その輝きにエスは手をのばした。炎がエスの
  掌に吸い込まれてゆく。

  『聖樹の炎。聖霊が残した痕跡のひとつ。

  火の聖霊は寒さに凍える人々を憐れみ，己の力を聖樹の火種に宿した。
  やがて人々によって火が弱まると，
  その願いにより聖霊は自身の魂を聖樹にくべた』

  最後の火を失った聖樹は，みるみるうちに全てを凍らせてゆき，その幹をひ
  び割れさせていく。悠久の時を生きた大樹が朽ち果てるのもそう遠くないだ
  ろう。

  エスは結晶石を使い最果ての地へ移動した。うなだれる剣士と黄銅の剣士が
  変わらずそこにいた。本来であれば二人に報告し，自身の進歩を告げるのも
  悪くないだろう。だが妹の情報を他の場所で探すことのほうが優先されるべ
  きことだった。

  次なる地へとエスは足を踏み出す。道を進むごとに，最果ての地に残る焚き
  火が小さくなり，やがて見えなくなった。そのときエスは，幻魔王の使い魔
  カーリオンに主の最期を告げるべきかをわずかに考えた。主を失った使い魔
  はその行く末をどうするのか。もしその姿を消し去ってしまったら，二度と
  魔術を教わることができなくなるのだ。

  だが魔術を善しとしないエスは，魔術の師がなくなることはさほど気にかけ
  ていなかった。それよりも自身の戦技を高めることを求めていた。これまで
  は奇跡的に勝利をつかんできたものの，生命力を犠牲にしながら戦うことに
  限界を感じつつあった。

  技術を学ばずとも妹を救えるならばそれに越したことはない。だがこれから
  自身が遭う戦いはより激しいものになるであろう。それらを乗り越えていく
  には聖都の中で黒檀の戦士としてより成長していくことが不可欠なのだ。

  <br>
  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/01.md][水の都ローメシア-01へ]]

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

