#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 燃えさかる腹-02

  暑さにエスは目を覚ました。眼前に結晶石と瓦礫の一部がある。周囲は見渡
  すかぎり赤熱した岩石に覆われていた。広大な空間は，その至るところから
  溶岩が滝を作り地形を浸食している。時折低くうなるような音がするのは，
  どこかで風が反響しているのだろうか。

  なんとか歩けそうな場所を探し，先へ進む。足場にも溶岩が流れる場所があ
  り，触れるだけで冷静さが大きく失われてゆく。仮に興奮状態であればあっ
  という間に生命力が尽きてしまうだろう。

  行き止まりについた。溶岩の沼がどこまでも広がっている。敵の気配を感じ，
  反射的に回避した。エスがすり抜けた物体は背後の壁に当たり，蒸気をはい
  て固まる。液状の溶岩を何かが打ち出してきたのだ。間もなくその主が姿を
  現した。

  打ち出される溶岩をかわしながらその正体を視界に収める。ウロコと尾をも
  つ何か。魚ではなく手足があることから，トカゲのような魔物であるとわかっ
  た。ドロドロの溶岩に巣喰うそれは大きくジャンプし，こちらを攻撃してく
  るのだ。

  攻撃やその正体は把握できたものの，エスには戦う手立てがなかった。一方
  的に放たれる溶岩をかわしながら周囲を探索する。やがて沼のそばにハシゴ
  があり，上に昇れるのがわかった。被弾して途中で落ちないようタイミング
  をはかり，一気に昇った。

  ところどころを石で組まれた通路があった。これまでに比べ溶岩の浸食を受
  けていないようにも見える。熱が届かないかわりにやや暗く，明かりが必要
  だった。

  松明を片手に進むと，通路のあちこちで息絶えた兵士の姿があった。生き延
  びようとしてこの場所を作ったのだろうか。だが彼らは力尽き，代わりにこ
  こを寝ぐらとしているものがいる。壁の向こうからそれは息を荒らげながら
  やってきた。

  鎖のついた鎌をぶらさげた巨大な人型の魔物。エスは暗がりに隠れ様子を伺
  う。ある程度進んだところでそれは向きを変え，もと来た道を戻り始めた。
  エスは背後から忍びよると，激昂し渾身の一撃をたたきつけた。

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/meltystomach/03.md][燃えさかる腹-03へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

