#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-02

  エスは囲まれないよう壁沿いに後退しながら，一人ずつ始末した。その死体
  はこれまでの人間から奪ったであろう魂をいくつかぶらさげている。エスに
  は経験値を稼ぐという趣味はないが，この魂を使えば特別な商人との取引が
  有利になるだろう。

  その先にいる敵の急所を背後から突き刺すと，それは目の前の崖をまっさか
  さまに落ちていった。この街の建物はあちこちが崩れ，それが新たな道を作っ
  ている。自身の位置を正確に把握すれば，素早く街を移動できるのだ。ただ
  し道を覚えるためにはこの領域に何度も通う必要があるのだが。

  崖から見回すと，遠方に先ほどとは違う水門と，そのそばに歯車があるのが
  見えた。そこで水路の方向を切り替えるのかもしれない。エスは場所を覚え，
  崖下に降りた。

  両脇を建物が塞ぐ狭い街路をエスは進んだ。道中，脇道から敵が現れたが，
  さほど負傷することなく倒すことができた。

  噴水のある広場に出た。当然水は枯れはてているが，地面には赤い血だまり
  の跡がそこかしこにある。そして噴水の周囲には聖都を守って勇敢に戦った
  兵士たちの鎧が散乱していた。

  金属がきしむ音とともに，それは姿を現した。二本の足で歩く巨大な豚。背
  中にはやせた人型の魔物が乗っており，それが豚を操っているようだった。
  豚は全身のいたるところを鎧で覆い，トゲのついた鉄球を腕にぶらさげてい
  る。その怪物は噴水の周囲を巡回していた。

  そしてその背後に例の歯車と，それを操作するであろうレバーが見えた。選
  択のときだった。レバーは錆びついているだろうが，程度によってはすぐに
  引くことができるだろう。そうすれば怪物に見つかっても攻撃を受ける前に
  退却することができ，先に進める。

  問題はレバーを引くのに時間がかかった場合だ。水路を動かせないだけでな
  く，無防備に敵の攻撃を受けることになってしまう。噴水に散らばる兵士の
  残骸を見れば，それがどれだけ危険かは明らかであろう。

  エスはおもむろに駆け出すと，背中を向けている敵にむかって全体重をのせ
  て切りかかった。

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/03.md][水の都ローメシア-03へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

