#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-05
  
  玉に仕込まれたおびただしい数の針はエスの半身につきささった。ナイフや
  曲刀ほどの出血はない。ゲルダがすかさず次の刃を投擲する。それをエスが
  転がるように回避した瞬間。

  何かが弾けるような音とともに，どす黒い液体が噴出するのが見えた。それ
  は暗がりに色を奪われたエスの血であった。半身を蝕む針は互いに擦り合い，
  バックステップやジャンプなどの激しい動きのたびに肉をずたずたに切り裂
  くのだ。エスが投擲を回避するのを読んだうえでの敵の戦術だった。
  
  寸前で回避することのできなくなったエスは，歩くような鈍重な動きで辛う
  じてナイフをかわす。エスの肉体が針をはきだすまでは守りに徹するしかな
  かった。それに対しゲルダの飛び道具が枯渇する様子は微塵も感じられない。
  
  こちらが近付くと一定の距離で相手は離れる。エスが劣勢であることは間違
  いないが，敵の攻撃間隔は一定で，極めて単調であった。ゲルダがナイフを
  取り出し，構える動きを見せたところでエスは駆け出した。直線的な軌道の
  それをたやすくかわし，投げ終えたばかりの無防備なところへ渾身の力で刃
  をつきたてる。

  血をふきだしたのはエスのほうだった。だがエスがゲルダにつきたてた刃を
  なぎはらうと，軌跡に沿うように血のカーテンがひかれた。細い身体を悶え
  させ，あとずさりしながらなおもナイフを取り出そうとするゲルダにエスが
  追撃をかける。

  エスの骨身が終焉を伝えた。構わぬ。ゲルダに投擲させる間もなく，滅多切
  りにした。ゲルダは手に持ったナイフを落とすと，膝をつき，力なくくずれ
  落ちた。同時に黒檀の戦士は三度目の大出血を起こし，その肉体は霞のよう
  に消滅した。
  
  <br>
  <br>
  水の都ローメシア-06へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

