#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-06

  入口の結晶石に復活したエスは，自身の半身が普段通りに動くのを確認する
  と，再び陰影の支配する建造物へと入っていった。水路の壁にはしごを見つ
  け昇ると，下からは見えなかった全貌が明らかになった。

  いくつもの建物がそびえ，その足下にはゴミのような塊がこびりついている。
  それはかつて大勢の人だったものが，弔われもせず朽ちたその果てである。
  見上げると建物の外壁には鉄柵のついた通路があり，ところどころに明かり
  がゆらめき，時に動くのがわかった。

  目を凝らすと，そのひとつひとつが敵のぶらさげた明かりであることがわかっ
  た。ここは魔物が密集した巣だ。それは水路を封鎖し，逃げ場を失った人々
  を残らず狩り尽くすと，なおも生者を求めてさまよっているのだ。

  正面の十字路中央に，鎖につながれた四つ足の獣の姿があった。全身を透明
  な石版で覆い，呑気に眠っている。先ほど聞いた声の主とは違うようだ。仮
  にこの獣を排除することができれば道を使って速やかにこの地域を探索でき
  る。だがエスの勘は，決して近付いてはならないと告げていた。

  やむなく手前の建物に入り，階段を上がる。足音が反響し潜行が妨害される。
  同時に，敵の足音が響くのも聞こえてくる。位置を把握して行動することが
  重要なようだ。

  この牢獄の番人は，曲刀を持った先ほどの敵と同類のようだった。だが武器
  の大きさ，鎧の重厚さから，怯まずに一撃をくりだしてくるだろう。この狭
  い通路で正面に立たれれば，かなり戦いにくい相手だ。

  エスは敵の巡回するのに合わせ後をつけると，背後から急所を串刺しにした。
  さすがの不意打ちに敵が倒れこむ。そのまま起きあがる前に攻撃を加えると，
  敵が正面で構える頃にはほぼ勝負は決していた。

  その死体も先ほどの敵と同様に魂をぶらさげていた。これが遠くから敵を照
  らしていた明かりの源だったのだ。弔えるかはさておき，エスは回収をする
  と鉄柵から周囲を観察した。この敵が一人だけなら背後からの攻撃で有利に
  戦える。二人以上に襲われないよう行動することを意識した。

  <br>
  <br>
  水の都ローメシア-07へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

