#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-07

  建物を順調に昇る最中，エスは奇妙な塊を見た。ホールのような開かれた空
  間の中央，暗がりのなかでそれは蠢いている。先に進むためにはそこを通ら
  ねばならなかった。覚悟を決めてエスが足を踏み入れると，四方八方から何
  かが飛びついてくる。

  それはエスの半身ほどの大きさもあるヒルのような魔物であった。全てをか
  わしきれずいくつか身体にはりつくと，それは衣服の上からも構わず猛然と
  身体をすすり始めた。エスはたまらず転がりながらなんとか引き離そうとす
  る。体液をしこたま吸ったそれはさらに大きくなり，久々の獲物を吸いつく
  そうとうねりながら近付いてきた。

  エスは刃を振り回しながらさらなる吸血を防ごうとする。そして刃に照らさ
  れた空間全体に，おびただしい数のヒルがへばりついているのを見た。ホー
  ル中央で蠢く塊は，おそらくヒルの親玉か巣のたぐいのものだろう。

  一旦退却し状況を整理することにした。フロア全体にヒルが満ちているとな
  ると，走って突破しようにも足をとられて時間がかかるだろう。とはいえ一
  匹ずつ倒しながら進むのは得策ではない。エスは先程切りつけたヒルへの感
  触から，ひとつの賭けに出た。

  エスはフロア入口で激昂すると，中央に向かって全速力で向かった。ヒルた
  ちが待ちかねたように飛びついてくるものの，へばりついたそばから融けて
  ゆく。冷静さを失ったエスの身体は激しい熱を帯びているからだ。だが激昂
  している間は生命力が失われる。そのため早くここを突破しなくてはならな
  い。

  それにも関わらずエスは中央へ向かった。元凶を断たねば後に響くかもしれ
  なかったためだ。だが切りつける前，想像を絶するおぞましい正体にわずか
  にたじろいでしまった。

  それは確かに孵化したばかりのヒル達の巣であった。ただしそれらに貼りつ
  かれ，養分とされていたのは，団子のように押し固められて蠢く人間達の塊
  であった。

  刃を握る腕から自身にためらいが生じているのを感じた。聖都のわずかな生
  き残りであると同時に，妹の行方の手がかりを持つかもしれないもの，そし
  て，もはや手遅れのものであった。残された体力はわずかである。決断しな
  ければならなかった。

  エスは悟り，肉塊に切りかかった。刃を振るうたびに血が飛散し，激痛に肉
  塊が震える。フロアの壁を引き裂かんばかりの叫び声が響いた。

  かつて人であったそれが魔の保育器としての機能を喪失したのを確認すると，
  残り体力がわずかであったエスは激昂を解き，ヒル達が近付かないことを祈
  りながら治癒を唱えた。そして再び激昂すると，群れの中を駆け，無心で上
  への階段を目指したのであった。

  <br>
  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/08.md][水の都ローメシア-08へ]]

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

