#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-08

  階段を昇り，きしむ扉を開け放つと建物の外に出た。陽を遮る天井付近には
  水を流すために使われたと思われるホースが縦横無尽に張り巡らされている。
  かつての天蓋は光を取り込むとともに雨を防ぎ，往来を途絶えさせないよう
  な仕組みになっていたのだろう。だが水の流れが途絶え，降り注ぐ塵によっ
  てこの地域は光の届かぬ場所となってしまった。

  ここから正面の梁をつたって隣の建物に移れるようになっていた。その建物
  からさらに梁が右方向に延び，ここから見て斜め向かいに渡れるようだ。エ
  スはまず隣の建物に移動することにした。

  梁は細く，地面は遥か下方にある。そこでようやく，ヒルに吸われ尽くされ
  た人間の塊が廃棄され，この建物の足元に広がっていたのだとわかった。

  エスはそのとき，先に斬った人間の感覚を思い出していた。自身の刃は魔物
  を断つためにあり，同朋の命を奪うためにあるものではなかったはずだった。
  妹を救うために，この先も聖都で人を殺めることになるかもしれないと考え
  ると，この国に入ったときの決意がわずかに揺らぐのであった。

  だが世の人々はエスの逡巡などどうでもよかった。聖都を巣喰う魔を断ち，
  自身の命が明日も続くことさえ期待できれば，そのためにどれほど一人の人
  間が傷つこうが構わないのだ。ゆえにエスにはその魂が擦り減ろうがひたす
  らに進むことが求められたのである。

  ふと梁の先から大曲刀の剣士が向かってくるのが見えた。後退しようと振り
  返ると，もと来た方角からも曲刀の剣士がやってきた。やつらはエスが梁を
  渡り始めるまで隠れていたのだ。ふだん慎重深い黒檀の戦士には考えられな
  いほどのミスであった。

  挟撃され，なすすべもなくエスは斬られた。態勢を崩し梁から足を踏み外す
  と，そのまま逃れられぬ死へと堕ちていったのだった。


  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/09.md][水の都ローメシア-09へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

