#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-11

  正面の壁には先の建物よりもはるかに大きな穴が開いており，そこから水路
  を挟んで向かいの景色が見えた。砂が時折落ちる音がするが，敵の気配はな
  い。

  ただし水路の向こう側，その壁に何かが座り込んでいる。腰から上だけでも
  エスの身の丈の十倍ほどはあろうかという巨躯。戦いになったとして，ここ
  で命を落とし，火薬玉なしでヒルに蝕まれた剣士に相対することになるのは
  避けたかった。

  倒れて道となった壁が崩れないか，確認しながら水路の上を渡ってゆく。そ
  してとうとう向かい側の地面に降り立った。

  近付いて改めてその大きさに舌を巻く。両腕をもがれ，腰を下ろすように佇
  むそれは全身を鎖と剣でめちゃめちゃに貫かれ，壁に固定されていた。それ
  にも関わらずいびきをかいている豪胆さに，敵ではないとエスは直感した。

  何度か話しかけると，その巨体は目を覚まし大きなあくびをした。

  「ふぁぁ… なんじゃ，もう用済みなのではなかったのか？
  ん？…おお！
  これは珍しい。まだこの国に生者がおったとはな。
  わしに何か用か？」

  目覚めた相手にエスは自身を伝え，妹の行方を聞いた。

  「黒檀の戦士…というのか。よくわからぬが，家族を探しておるのだな。
  あいにくだが，ここによそ者は来ておらんよ。
  わしらがここの民を守るために道を塞いだからの。」
  
  相手の素性についてさらに話を聞いた。

  「わしらは聖霊が消えたあとここへやってきた。
  そして残された人々を守るために魔物と戦った。
  だがの，ここはとんでもない魔境じゃったよ。
  人の欲望をかきたてるのじゃ。
  わしは抗ったが，部下だけじゃない，相棒にまで裏切られてこのざまよ。
  はっはっは。

  ……。
  おぬし，戦士ならば，わしの頼みを聞いてくれぬか？
  わしの相棒を倒してほしいのじゃ。
  名をブラントキウムという。
  今頃は己の欲望のまま，あらゆるものの命をすすっていることじゃろう。
  わしはそれが耐えられん。お願いじゃ。
  もちろんただとは言わん。わしの技をおぬしに伝授してしんぜよう。

  なに，この姿で教えられるかとな？
  老いても剣聖，おぬしの腕はひと目で丸わかりよ。

  さて，何が知りたいのじゃ？」

  エスは戦技の達人と出会ったことに感謝し，戦技「鉄身」「こだま」を学ん
  だ。
  
  「また来るがよい。相棒のことは頼んだぞ」

  思わぬ収穫にエスは感謝し，付近の探索をはじめた。

  <br>
  <br>
  水の都ローメシア-12へ

  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]
  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

