#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 水の都ローメシア-12

  水路を切り替えるレバーは，瓦礫で塞がれた水路の近く，目立たないところ
  にあった。そこから罪なき咎人ゲルダと死闘をくりひろげた場所が見下ろせ
  る。エスがレバーをひくと，壁の錆び付いた歯車が回り出し，轟音とともに
  地面が揺れた。同時に，水路の上を橋渡ししていた瓦礫が崩れ落ちる。

  瓦礫は激しい衝撃とともに水路の一部を粉々に砕いた。降り積もった瓦礫は
  水路の上へと続く新たな道となったのだ。これで建物群を経由しなくとも戦
  技の達人に会いに行けるだろう。

  エスが外に出ると，先ほどのレバー操作によって水路が回転していた。道は
  ここから見てT字を描いており，一方は結晶石，そしてもう一方が門へとつ
  ながっていた。その口を閉ざしていた鉄格子も今はなく，命知らずの戦士を
  待ち受けている。

  エスは一度結晶石へと戻り，刃を手入れすると，門へと向かった。石を蹴る
  足音が耳へ響くほど，集中が増しているのがわかる。ついに門の前へ立つと，
  先へ進む前に，改めてそれを眺めた。これまでの激闘が嘘のような静寂に，
  鼓動が早まる。

  意を決して門に手をかけ，体重をのせて奥へと開いた。猛烈な屍臭が鼻をつ
  く。

  開かれた先に足を踏み入れると，光が届かず何も見えない。松明に火をつけ
  足場を確認した。地面には謎の液体が張っており，足音が粘り気を帯びる。
  数歩進むと，不意に門が閉じられた。松明の明かりさえ吸い込まれそうな完
  全な暗闇である。

  すると奥のほうで何か液体の落下する音がした。直後に強烈な閃光が生じ，
  暗闇に慣れたエスの視界が塞がれる。光が間もなく弱まると，光源の正体が
  あらわになった。

  浄化者オーンソール。光る球体を不定形の液体で覆ったそれは，エスを排除
  すべき対象と認識したようだった。

  決戦が始まった。

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/lawmessiah/13.md][水の都ローメシア-13へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

