#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 風の渓谷-01

  最果ての地から最も離れた場所，風の聖霊が守護する領域があった。聖霊の
  地へは風の渓谷を抜け，聖都アーケイで二番目に栄えた都市である風車街ポ
  レアニスを越える必要がある。松明を手に道なりに進んでいたエスは，やが
  て寒さにも依らずにその火が消えるのを見た。

  強烈な悪臭。

  空気は淀み，風の渓谷と呼ばれた崖の谷間には瘴気が満ち満ちていた。瘴気
  の刺激にやられ，涙で視界がにじむ。それだけでなく，重く濁った気体が周
  囲を覆い，濃霧のように目の前に広がる世界を塞いでいた。

  灰黒の気体は空からそそぐ光を奪い，方向感覚を奪う。自分が今いる場所を
  忘れたら最後，永遠にこの淀んだ地をさまようことになるだろう。エスは決
  して道を忘れないよう，一歩一歩足を進めた。

  最も厄介なのは，場所の高さによって瘴気の濃度が異なることだった。特に
  周囲と異なるほど色の濃い部分は黒檀の戦士の強靭な肉体をも蝕む。やがて
  毒に侵されると，焦りによって冷静さが回復しなくなってしまう。時間がた
  てば毒は癒えるものの，毒に侵された状態で敵と戦うのは無駄に肉体を焦が
  すことになるのだ。

  視界の悪さ，毒に加え，迷路のように高低差がある地形がエスを苛立たせた。
  そしてこの状況でも有利に戦える唯一の戦術も理解していた。

  魔術である。

  魔術は詠唱こそ必要なものの，冷静さを失わず，離れた敵も攻撃できる。す
  なわち毒にかかった状態で高低差のある敵にも不利なく戦えるのだ。リギュ
  ラの炎塔にてカーリオンに魔術を学び，詠唱のための持久力を鍛えておけば
  この地でも苦戦することなく進むことができたであろう。

  しかしエスは自身の強い信仰心から魔術に頼ることを潔しとしなかった。ゆ
  えにここまで治癒を除いて魔術を使うことは殆どなかったのだ。そのエスの
  信念は揺らがず，たとえ自身の選択が己を苦しませることになろうと，決し
  て折れずに乗り越えてみせると心を奮い立たせていた。
  

  <br>
  <br>
  風の渓谷-02へ


  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

