#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-02
  
  エスは道を襲いかかってくる影達に全身全霊で斬りかかった。一撃で体勢を
  崩した影にすかさず返しの二撃目が入り，黒い霧を吐きながら影は消えた。
  エスが刃を振るうたびに灼けつく炎の筋が残光のように輝く。やがて道を覆
  いつくすほどであった影の群れもひとつ残らずかき消された。

  だがエス自身も全身から焦げたつ煙を放ち，燃えつきる寸前であった。視界
  はほぼ失われ，肺も焼け，深く息をすることさえできない。治癒を唱えなが
  らなんとか意識を保った。

  黒檀の戦技のひとつ「激昂」は，冷静さを失ううえに生命力が時間とともに
  減少するかわり，刃の攻撃範囲と威力が格段に上昇する技である。当然のこ
  とながら生命力が減少しているところに敵の攻撃を受ければ命はない。しか
  し激昂を使わず大勢の敵を相手にするのは最悪の状況を迎えることになる。
  そこで守りを捨て高火力で殲滅する方法をとったのだ。

  生命力がある程度復活すると，エスは周囲を確認しながら慎重に進んだ。す
  ると，影が飛び出したあとの壁は磨りガラスのようにぼやけていることがわ
  かった。影が現れる壁には特定のパターンがあるのかもしれない。それがわ
  かれば待ち伏せも可能だ。今，エスの動きはあちこちの壁に反射し敵からは
  丸わかりになっている。極めて危険な状態であった。

  道の両脇はどこまでも建物が続いている。どの入口も固く封じられ開く気配
  はない。だがいつまた先程のことが起きてもいいように，エスは隙を見せな
  かった。

  やがて行き止まりに門の開かれた一際大きな建物が見えた。その屋敷の扉は
  軽く開かれた形跡がある。先客がいるのだ。それが先にエスが見た者の正体
  かはわからない。いずれにせよ進むためには中に入るしかなかった。


  <br>
  <br>
  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/ligulastower/03.md][リギュラの炎塔-03へ]]


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

