#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-02
  
  エスは襲いかかってくる影達に全身全霊で斬りかかった。攻撃は正確だった。
  一撃で体勢を崩した影にすかさず返しの二撃目が入り，黒い霧を吐きながら
  影が消える。エスが刃を振るうたび，灼けつく炎の筋が残光のように輝いた。
  やがて道を覆いつくすほどであった影の群れもひとつ残らずかき消された。

  だがエス自身も全身から焦げたつ煙を放ち，燃えつきる寸前であった。視界
  はほぼ失われ，肺も焼け，深く息をすることさえできない。治癒を唱えなが
  らなんとか意識を保った。

  黒檀の戦技のひとつ「激昂」は，冷静さを失ううえ，生命力が時間とともに
  減少するかわり，刃の攻撃範囲と威力が格段に上昇する技である。猛りと異
  なるのは，激昂で朽ちた肉体は冷静さを取り戻しても再生しないことである。
  当然のことながら生命力が減少しているところに敵の攻撃を受ければ命はな
  い。しかし激昂を使わず大勢の敵を相手にするのは最悪の状況を迎えること
  になる。そこで守りを捨て高火力で殲滅する方法をとったのだ。

  生命力がある程度復活すると，エスは周囲を確認しながら慎重に進んだ。す
  ると，影が飛び出したあとの壁は磨りガラスのようにぼやけていることがわ
  かった。影が現れる壁には特定のパターンがあるのかもしれない。それがわ
  かればこちらからの待ち伏せも可能だ。今，エスの動きはあちこちの壁に反
  射し敵からは丸わかりになっているという，極めて危険な状態なのだ。

  道の両脇はどこまでも建物が続いている。どの入口も固く封じられ開く気配
  はない。だがいつまた襲撃されてもいいように，エスは隙を見せなかった。

  やがて行き止まりに門の開かれた一際大きな建物が見えた。その屋敷の扉は
  軽く開かれた形跡がある。先客がいるのだ。それが先にエスが見た者の正体
  かはわからない。いずれにせよ進むためには中に入るしかなかった。


  <br>
  <br>

  [[./03.md][リギュラの炎塔-03へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

