#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-03
  
  屋敷は一層濃い冷気に満たされていた。エントランスからすぐ正面が階下へ
  続く吹き抜けになっている。何者かの発する音が響いた。エスが音をたてな
  いように近づくと，吹き抜けから見えるホール中央に溶岩のような塊がある。
  それが蒸気を噴き出しながら唸り声をあげているのだ。

  その塊が唸るたびに溶岩の隙間から赤い光がさすのが見える。気配から察す
  るに眠っているようだった。不要な戦いを避けるため，エスは静かに階段を
  下った。豪奢な屋敷には不釣り合いなほどその階段はたよりなく，一歩ごと
  に不快な音をたてた。エスは溶岩の塊に気付かれないよう慎重に進む。

  ようやく階下のホールにたどりつくと，正面に大扉があり，左手は光届かぬ
  奥の通路へつながっていた。大扉は鍵がかかっているが，明かりなしに通路
  を進むのは無謀である。かといって，この寒さでは松明を灯そうにもすぐに
  消えてしまうだろう。

  エスは猛り，刃の残光が道を照らすか試したが無駄骨であった。やむをえず
  エスは大扉の鍵を探すため再び階段を登った。

  エントランスからは階下正面の大扉が見え，左手に窓明かりのさす通路があ
  る。鍵があるならばその方角だろう。通路には窓に照らされたいくつかの部
  屋がある。ドアが破損し，中に入れない部屋もあった。エスはまず一番手前
  にある部屋のドアに手をかけた。

  目の前を一筋の線がはしった。

  ドアとともにエスは対角線に両断された。

  だがエスは読んでいた。手をかけたと同時に後方にステップし，その攻撃を
  やりすごしたのだ。すかさず正体不明の敵に数太刀あびせる。くぐもった声
  をあげて相手は倒れた。先ほど戦った影とは違う，武器を持った剣士のよう
  であった。主なき後，火の領域を守り，狂気に侵された聖都の戦士だろうか。

  部屋の中は衣類や家具などが散乱し，はっきりとは見えないものの天井まで
  飛び散った液体の痕がある。この部屋には目的の鍵はなさそうだ。エスは部
  屋を出た。隣の部屋はドアが破壊され，中に入れそうにない。その奥にある
  部屋の方へ進んだ。

  先ほどのように警戒しながらドアに手をかける。敵の気配はない。すると，

  窓ガラスが割れる音とともに，後ろからエスは串刺しにされた。

  <br>
  <br>
  [[./04.md][リギュラの炎塔-04へ]]


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

