#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-04
  
  影は窓の外に潜んでいた。背後からの攻撃は正面よりもダメージが大きい。
  なんとか踏みとどまり，エスが後方に避けると，別の窓からも影が登ってき
  た。敵はエスをこの通路で挟み撃ちにするため，窓の外にしがみついて隠れ
  ていたのだ。

  エスは正面から斬りつけてくる敵に合わせ，カウンター攻撃を決めた。その
  まま相手がのけぞるのに合わせて脇をくぐり抜ける。窮地を脱しエントラン
  スまで後退したエスは，落ち着いて治癒を唱え，追ってくる敵を始末した。
  がむしゃらに攻撃せず，カウンターを決めたことで何とか生き延びられたが，
  紙一重の戦いであった。

  改めて奥の部屋に向かい，入り口の壁に隠れていた影を倒してからあたりを
  見回した。殺風景な部屋には，貴重品の入った箱と，壁にぶらさがり鈍く光
  を反射する鍵があった。おそらくこの鍵で階下の扉を開けられるだろう。ま
  た箱には武具の一種が収められていたが，エスには慣れ親しんだ刃を持ち替
  える気はなかった。

  再び吹き抜けのところに戻り，階下を見やる。戦いがあったにも関わらず溶
  岩に目覚める気配はなかったのは幸運であった。エスは慎重に階段を下る。

  ところが，石の砕ける音とともに階段が崩れ，エスは階下に叩きつけられて
  しまった。迂闊。目の前が明るくなる。溶岩の隙間から炎が赤あかと燃え出
  し，部屋全体が揺さぶられる咆哮とともに塊が動きだした。

  それは異常に発達した両腕ではいつくばりながら，力まかせに拳を振り回し
  てきた。エスは巧みに避けるが，ここは狭すぎる。溶岩塊を大扉からなんと
  か引き離すと，隙をみて扉に駆けた。

  鍵が束でなかったこと，また鍵穴が一致したことに感謝しつつ，エスは扉を
  開け放った。

  断崖と，無限の暗闇がどこまでも広がっていた。

  <br>
  <br>
  リギュラの炎塔-05へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

