#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-05
  
  リギュラの炎塔入り口に復活したエスは，自身の不甲斐なさを恥じるととも
  に，一旦退くかどうか思案した。この数刻で二度も死ぬということは，それ
  だけ困難な領域であるということか。しかし敵に歯が立たぬというわけでは
  ない。エスは進むことにした。

  屋敷に近付くと，目覚めた溶岩塊が吠えているのが外からでも聞こえてくる。
  エスは意を決して中へと入った。

  崩れた階段から階下に飛び降りると，すかさずこちらを捉えた溶岩塊が激し
  く攻撃を加えてくる。エスは先刻自身の命を奪った大扉を憎々しい目で見つ
  つ，その左へ駆けた。

  溶岩塊の熱が放つ光が通路を照らし，奥に扉があるのが見えた。それと同時
  に通路の隅にうずくまっていた敵の影が照らし出される。溶岩塊が目覚める
  前にここに立ち入っていたら三度目の死を賜わるところであった。

  溶岩塊の攻撃をある程度見切りながら，エスは慎重に通路の影を倒していき，
  扉にたどりついた。再び溶岩塊の隙をぬって鍵を開け，扉を開く。

  エスは溶岩塊とともにテラスに出た。火は失われたものの壮大な街並みが周
  囲に広がっている。だが重要なのは先に進むことだ。見渡すと行き止まりの
  ようだが，テラスを出て右側にもこちらと同様の足場があり，さらにその先
  には炎塔入り口の門と同じ模様の壁が見えた。

  必ず隣の足場に移る方法があるはずだ。エスは手がかりを探した。するとテ
  ラス右側の手すりが崩れかかっているのがわかった。自身の腕で壊すことは
  できないが，溶岩塊なら。しかしこれまで大振りの攻撃を距離をとってかわ
  してきたものの，腕の届く範囲で攻撃を受けたことはない。万一手すりを背
  にして腕に当たれば，手すりの残骸ごと崖下に命を捨てることになるだろう。
  
  エスは手すりを背にし，溶岩塊の腕に集中した。



  <br>
  <br>
  リギュラの炎塔-06へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

