#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-06
  
  溶岩塊が大きくふりかぶって右腕をなぎ払ってきた。エスはその左腕に回り
  込むように飛び退く。腕の範囲は想像よりも広く，溶岩塊の背中付近まで迫っ
  た。エスは背中にすさまじい熱を感じる。だが剛腕は崩れかけだったテラス
  の外枠を粉々にうちくだいた。

  背中の火の粉を払いながら，エスは距離をとって溶岩塊を誘い出す。相手が
  這ってくるのにあわせてその巨体をすり抜け，テラスの端から渾身の力で飛
  びあがった。

  ふと見下ろした。眼下，そのはるか先の暗闇に巨人が闊歩する姿があった。
  間もなく石の地面が姿をあらわし，エスは転がりながら着地した。隣の足場
  に見事飛び移ったのだ。

  直後，足に鋭い痛みを感じた。足場のそばに隠れていた槍の剣士に貫かれた
  のだ。溶岩塊の猛攻をくぐり抜けた余韻すら敵は与えてくれぬようだ。足場
  は狭く，下手に攻撃を避ければ落下してしまう恐れがある。エスは慎重に相
  手の攻撃を見切り，初段の突きにあわせてカウンターを決めた。

  剣士の死体にひっかからないようにして，エスは足場から奥に進んだ。そこ
  から階段を経て，大きな壁の前にたどり着いた。

  予想していた通り，その壁はリギュラの炎塔入り口に続く門であった。取り
  付けられてからさほど時間が経っていないであろう木製の閂を壊し，全体重
  をかけて門をこじあける。そしてエスは見知った結晶石の前に腰をおろし，
  しばしの休息をとったのであった。

  <br>
  <br>

  [[./07.md][リギュラの炎塔-07へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

