#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-07

  エスは軽く刃の手入れをし，門の先に進んだ。正面は大通りに面し，その先
  に目的地となる炎塔がある。大通りから延びた十字の道は湾曲し，その道に
  そって建物が並んでいる。炎塔を中央にして円形に街並みがつくられている
  ようだった。

  エスはこれまでと同様に，慎重に進んだ。途中，壁や道の角から幾人かの影
  が現れたが，後退しながら敵をおびきだし各個撃破していった。これまでの
  ような罠には感じられず，不気味であった。もしくはエスの敵への対処が上
  達しているということだろうか。

  ふと正面の何もない空間が歪むと，赤黒い影をまとった剣士が現れた。これま
  での敵とは明らかに違う，すさまじい殺気を帯びていた。こいつはとてつも
  なく強い。

  生命狩りの狂者ナルチル。上半身を長いマントで覆っている。それは迷いな
  くこちらに駆け寄ると，両手の武器を構えて突進してきた。辛うじてエスが
  横にステップすると，甲高い金属音とともにナルチルの武器が閉じた。両手
  に持っていたのは二本の剣ではなく，大バサミであった。開いた時に比べ，
  閉じた際のリーチは極めて長い。背後にステップするのは危険だ。

  突進だけでなく，相手は閉じたハサミを大剣のように振り回してくる。ただ
  し，ハサミが重いのか攻撃後の隙は大きい。そこをエスは見逃さず攻撃した。
  ナルチルがよろけつつも反撃するのをかわし，距離をとって出方をうかがう。

  敵が積極的に攻撃してくるのは幸運であった。相手の隙に合わせ攻撃を当て
  れば戦いを有利に進められる。現に，ナルチルの生命力は確実に減っていっ
  た。
  
  ナルチルの体力が半減した頃だった。こちらに背を向け逃げ出し，治癒で回
  復をはかろうとしてきたのだ。それを防ぐためエスがあとを追った瞬間，

  轟音とともに背後の道が巨大な壁で塞がれた。しかもそれに合わせるように
  建物の壁を破って影達が現れたのである。あまりにもあっけなく敵の罠に落
  ちたことにエスは憤慨した。体力を回復したナルチルは影とともにこちらの
  命を刈り取ろうとするだろう。だが何としてでも返り討ちにしてやろうとい
  うエスの強い決意があった。


  <br>
  <br>
  リギュラの炎塔-08へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

