#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-07

  エスは軽く刃の手入れをし，門の先に進んだ。正面は大通りに面し，その先
  に目的地となる炎塔がある。大通りから延びた十字の道は湾曲し，その道に
  そって建物が並んでいた。炎塔を中央にして円形に街並みがつくられている
  ようだった。

  エスはこれまでと同様に，慎重に進んだ。途中，壁や道の角から幾人かの影
  が現れたが，後退しながら敵をおびきだし各個撃破していった。これまでの
  ような罠は感じられず，不気味であった。もしくはエスの敵への対処が上達
  しているということだろうか。

  ふと正面の何もない空間が歪むと，赤黒い影をまとった剣士が現れた。これ
  までの敵とは明らかに違う，すさまじい殺気を帯びていた。強い。黒檀の戦
  士でなくともそう感じただろう。

  生命狩りの狂者ナルチル。上半身を長いマントで覆っている。それは迷いな
  くこちらに駆け寄ると，両手の武器を構えて突進してきた。この攻撃は下がっ
  てかわしてはいけない，というエスの直感がはたらいた。辛うじてエスが横
  にステップする。甲高い金属音とともにナルチルの武器が閉じた。両手に持っ
  ていたのは二本の剣ではなく，大バサミだったのだ。開いた時に比べ，閉じ
  た際のリーチは極めて長い。エスの勘は正しかった。

  突進だけでなく，相手は閉じたハサミを大剣のように振り回してくる。変幻
  自在の攻撃に当初エスは回避する一方であった。だがやがて，ハサミが重い
  のか攻撃後の隙は大きいことに気づいた。そこをエスは見逃さず攻撃する。
  ナルチルがよろけつつも反撃するのをかわし，距離をとって出方をうかがっ
  た。

  敵が積極的に攻撃してくるのは幸運であった。相手の隙に合わせ攻撃を当て
  れば戦いを有利に進められる。現に，ナルチルの生命力は確実に減っていっ
  た。
  
  勝利の予感をエスがうっすらと感じたのは，ナルチルの体力が半減した頃だっ
  た。こちらに背を向け逃げ出し，治癒で回復をはかろうとしてきたのだ。そ
  れを防ぐためエスがあとを追った瞬間，

  轟音とともに背後の道が巨大な壁で塞がれた。しかもそれに合わせるように
  建物の壁を破って影達が現れたのである。ナルチルがこちらが罠にかかった
  のを確認するように，悠々と体力を回復させる。幾度も罠にかかり，エスは
  屈辱であった。全快のナルチルは影とともにこちらの命を刈り取ろうとする
  だろう。だが何としてでも返り討ちにしてやるというエスの強い決意があっ
  た。


  <br>
  <br>
  リギュラの炎塔-08へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

