#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-08

  道幅の広さを活かし，エスは敵に囲まれないよう距離をとりつづけた。これ
  までの戦いで敵は誰一人として遠距離攻撃を持っておらず，統制のとれた動
  きはできていない。それを利用して徹底した持久戦を選んだのだ。

  影の数は多く，エスが刃を振れるチャンスは少ない。また一度でも囲まれた
  り，攻撃を受けて怯むようなことがあれば，たちまち命が奪われてしまうだ
  ろう。薄氷の上を渡るような緊張感のなかで，エスの集中は高まっていた。

  影達は不規則なリズムで攻撃してくる。しかし見極めれば，回避するだけな
  らさほど難しくない。しかも影の群れが邪魔をして，ウティカはこちらに思
  うように攻撃ができなかった。それに対してエスはわずかながらも攻撃の届
  く範囲の相手に着実にダメージを与え，影の数を減らしていった。

  だが影の数が減るということは，同時にウティカの自由な攻撃を邪魔する者
  も減ることを意味した。影の数が残り2体となったところで，エスは回避す
  る一方になってしまった。ウティカと影の波状攻撃が読みきれず，囲まれな
  いように逃げるだけで精一杯なのだ。

  多数を相手にしてきたエスの疲労は激しく，確実に生命力が削られてゆく。
  そのなかでもエスはあきらめず，ついに最後の影を倒した。改めてウティカ
  との一対一の戦いである。

  集中が途切れがちになり，早く勝負をつけようという意識がもちあがる。し
  かしそれは一撃の重い相手との戦いでは死を急ぐようなものである。じれっ
  たさと苦痛，様々な葛藤を経て，エスはついにウティカを倒した。赤黒い影
  が倒れるように消えると，収束して光になった。

  『浄血のマント

  生命狩りの狂者ウティカがまとっていたマント
  元は純白の輝きを放っていたようだが
  返り血によって赤く染まってしまっている

  装飾はほとんどかすれてしまっているものの
  縁にわずかに残る金色の装飾は聖職者の証である』

  エスが周囲を見回すと，壁は複数の道にわたってせり立っているようであっ
  た。町はそのまま敵の侵攻を防ぐ城塞かつ迷路として機能しているようであ
  る。中央の炎塔に至るすきまを探して，エスは壁づたいに道を進んだ。

  <br>
  <br>
  リギュラの炎塔-09へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

