#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-10

  どこから攻撃されるかわからない危険のなかでも，エスは相手の姿を捉える
  糸口を探していた。足跡を探して敵の位置を把握しようとしたが，地面が石
  でできているため困難であった。相手の痕跡になりうるのは武器を振る際の
  音だけである。

  あまりにも一方的な戦いに，エスの心は千々に乱れていた。敵の笑い声から，
  黒檀の戦士など所詮はこの程度か，そんな挑発が聞こえてくるように感じら
  れた。

  そのとき，胸に下げた銀のペンダントが光にきらめいた。それはエスを励ま
  す妹の願いであったか。エスは再び自身を奮い起こさせ，同時に何かが脳裏
  をかすめた。

  冷気と実体のない敵と氷板。エスの思考は急速に研ぎ澄まされ，ついにひと
  つの可能性にたどりついた。

  それを確かめる必要がある。エスは不意に立ちどまった。

  無防備のエスの背後に，カーリオンの鎌が迫る。大きく振りかぶり，首元へ。

  その姿が，氷板に映し出されていた。

  エスが転がりこむ。鎌は氷板を両断し，氷は砕け散った。想像したとおりで
  あった。このエリアの影は鏡のような氷の膜から現れた。その元締めである
  カーリオンの幻影化はより巧みであったが，それでも鏡に映る姿までは消す
  ことはできない。

  元々あった氷板は5枚。今残っているのは4枚。敵を捉える唯一の手がかりが
  全て破壊される前に倒す。エスの刃は猛り，獲物に食らいつこうとしていた。
  

  <br>
  <br>
  リギュラの炎塔-11へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

