#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-12

  姿を見せたカーリオンは，エスの腰ほどの背丈しかなかった。鎌はその背よ
  りもはるかに長く，また身にまとっていた衣装は，黒く薄い生地にフリルが
  飾られた，凡そ戦いに向いているとは思えないものだった。

  「その武器，やはり黒檀の戦士か。
  噂には聞いていたがこれほどとは。
  貴公ならもしくは…
  いや，何でもない」

  こちらに攻撃してくる様子はなさそうだった。エスは不意打ちに警戒しつつ
  も話を聞いた。

  「私はカーリオン。
  こう見えても幻魔王の使い魔だった。
  幻魔王の名は知っているな？
  私はこれまで数多くの魔術師を見てきたが，
  彼は本当の天才だったよ。
  尤もここに来ておかしくなってしまったようだが。
  ハハハ…」

  エスは多弁なカーリオンに妹を知らないかを尋ねた。

  「妹を探しているのか？
  生きた人間にはしばらく会っていない。
  他のところを探した方がいいだろう。

  幻魔王に会いたいなら，生きてこの先に行ければ会えるはずだ。
  だがもう彼の魔術を見ることはできないだろうな」

  魔術について尋ねると，予想外の返事があった。
  
  「魔術に興味があるのか？
  黒檀の戦士とあろうものが，望外だ。
  まあ，命も見逃してもらったことだ。
  素質があれば簡単なものなら教えられるだろう」

  エスはカーリオンから，最も基本的な攻撃魔術『魔術の矢』を教わった。魔
  術詠唱にはスタミナが使われ，詠唱時間の長さによって攻撃力が3段階まで
  上がる。武器攻撃と違って攻撃に時間がかかり，ひるむと詠唱が中断される
  代わりに，魔術で攻撃しても冷静さを失わないのが強みだ。

  「魔術を知りたかったらまた来るといい，黒檀の戦士」

  エスは礼を言って先に進んだ。カーリオンが手を振って見送る姿に，エスは
  妹の姿を重ねた。そして颯爽とその場を後にしてしまったがゆえに，なぜカー
  リオンがここを守っていたのかを聞きに戻るのがためらわれたのだった。

  <br>
  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/articles/meltystomach/01.md][燃えさかる腹-01へ]]

  <br>

  [[https://github.com/jamcha-aa/EbonyBlades/blob/master/README.md][目次へ戻る]]

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

