#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* リギュラの炎塔-12

  姿を見せたカーリオンは，黒く薄い生地にフリルが飾られた，凡そ戦いに向
  いているとは思えない衣装をまとっていた。

  「あー怖かった。 ねぇキミ，強いね。
  どこの人？

  黒檀の戦士？知らないや。ハハハ…
  …ごめん。
  
  私はカーリオン。
  こう見えても幻魔王の使い魔だったんだ。
  幻魔王は知ってる？
  これまで数多くの魔術師を見てきたけど，
  彼は本当の天才だったよ。
  尤もここに来ておかしくなっちゃったけどね。
  ハハハ…」

  エスは多弁なカーリオンに妹を知らないかを尋ねた。

  「そういえばどうしてこんな所にいるの？
  妹？生きた人間にはしばらく会ってないけどなぁ。
  他のところを探した方がいいんじゃない？

  幻魔王に会いたいなら，この先に行ければ会えると思う。でももう彼の魔術
  を見ることはできないんじゃないかな」

  魔術について尋ねると，予想外の返事があった。
  
  「魔術に興味があるの？
  素質があれば簡単なものなら教えられるけど。
  命も助けてもらったしね」

  エスはカーリオンから，最も基本的な攻撃魔術『魔術の矢』を教わった。魔
  術詠唱にはスタミナが使われ，詠唱時間の長さによって攻撃力が3段階まで
  上がる。武器攻撃と違って攻撃に時間がかかり，ひるむと詠唱が中断される
  代わりに，魔術で攻撃しても冷静さを失わないのが強みだ。

  「魔術を知りたかったらまた来てね，戦士さん」

  エスは礼を言って先に進んだ。カーリオンが手を振って見送る姿に，エスは
  妹の姿を重ねた。そして颯爽とその場を後にしてしまったがゆえに，なぜカー
  リオンがここを守っていたのかを聞きに戻るのがためらわれたのだった。

  <br>
  <br>
  燃えさかる腹-01へ


  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

