#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 最果ての地-03

  エスはペンダントをしまうと，柱のそばに立つ人物にも話を聞くことにした。
  柱の影でわからなかったが，それは全身を黄銅の甲冑で覆った剣士であった。
  鎧に擦れた痕や欠けたところもなく，それでいながら腰に差した剣は使いこ
  まれており，かなりの手練れであることがうかがえた。

  「ふむ…黒檀の騎士か。珍しい。
  この地に何の用だ。
  名をあげるつもりで来たのか？ 他の英雄のように」

  仰々しい甲冑には似合わない鈴の音のような美声であった。エスは聖都に至っ
  た経緯を伝えた。

  「妹を探しているのか。残念だが私は会っていない。
  ここに来たばかりなのでね。
  それどころかなぜここに来たのかもほとんど覚えていないのだ。
  滑稽だろう。フフッ…」

  剣士は視線をまっすぐに戻して話を続けた。

  「私はこの国で何かを守る騎士だった。
  だが誰の騎士かも，何を守っていたのかも忘れてしまったよ。
  それでも鮮明に残るものがひとつだけある。
  この国に古くから伝わる伝承…
  
  『聖難の時，いずこより救世使あらわれ，
  預言に依りて聖霊を従えん時，
  月の都は其の門を開き，
  此の地に永遠の清浄をもたらさん』
  
  私はこの詩が記憶を取り戻す重要な手がかりだと思っている。
  聖霊を従えることが鍵のようだが，
  各地はこのありさまだ。はたして聖霊はどこに行ってしまったのか…」

  エスは剣士から再びその詩を聞き，心に留めた。そして火，風，水，地の各
  領域で無闇に妹を探すだけでなく，聖霊の痕跡も追うことが重要であると感
  じていた。エスが覚悟を決め魔物の巣窟に足を踏み出したとき，後ろから黄
  銅の剣士が激励の言葉を投げかけた。

  「達者でな。互いに生きて再会することを祈ろう」
  
  <br>
  <br>
  リギュラの炎塔-01へ

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is under a [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][License Creative Commons Attribution Non Commercial Share Alike 4.0 International]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

